### ISSUE TITLE
Incorporate ICDO mappings from progenetix

### ISSUE THREAD

**Issue by cmungall** [monarch-initiative/mondo#1148]
Currently we have ICDO mappings souirced fro NCIT, of the form `ICDO:nnnn/n'

progenetix has more complete mappings
https://github.com/progenetix/ICDOntologies/tree/master/current

TODO: determine consistency of these two

We will likely want to map each cancer term in mondo to a pair icdot/icdom as in the above.

E.g.

https://github.com/progenetix/ICDOntologies/blob/master/current/icdom-84303%2Cicdot-C34.9.yaml

```
equivalents:
- label: Lung mucoepidermoid carcinoma
  id: ncit:C45544
examples:
- labels: Lung mucoepidermoid carcinoma [cell line EPLC-272H]
input:
- label: Mucoepidermoid carcinoma
  id: icdom-84303
- label: Lung and bronchus
  id: icdot-C34.9
```

This could be formalized by an equivalence axiom between precomposed mondo class and class expression `icdom AND disease-has-location some icdot`

However, for convenience we may want to make simple xrefs to a conjoined string and have this resolve to URLs like https://progenetix.org/api/ncitcodes/icdom-85003,icdot-C50/

todo: determine license of progenetic mappings

cc @mbaudis 

Map each mondo class with an ncit equivalent to a icdot/icdom combo, see https://github.com/progenetix/ICDOntologies/tree/master/current

What is the license of these mappings?
