### ISSUE TITLE
review "muscle tissue disorder" branch

### ISSUE THREAD

**Issue by sabrinatoro** [monarch-initiative/mondo#6008]
following https://github.com/monarch-initiative/mondo/issues/5658 and meeting with experts on March 2nd, 2023. 

A lot of changes have been done directly on the existing PR during the call. 
Please refer to the https://github.com/monarch-initiative/mondo/pull/5984 to see the changes made in the classification 

In addition, some terms were put on the obsoletion list, and additional classification needs to happen. Decisions and discussions are [here](https://docs.google.com/spreadsheets/d/1zf-8lMPD9qn4LBTgnWtqDYDr6B6xkjlciawj_ky0d34/edit#gid=0)

**Comment by sabrinatoro** [comment]
In addition to these changes, (and maybe in the long term) we can review the genetic skeletal disorders following this paper: https://onlinelibrary.wiley.com/doi/10.1002/ajmg.a.63132

**Comment by sabrinatoro** [comment]
**Candidate for obsoletions:** 

Mondo ID | Label | Term tracker item | Consider | Consider label | Obsoletion reason (choose from dropbown) | Exclusion reason
-- | -- | -- | -- | -- | -- | --
MONDO:0016118 | muscular glycogenosis' | https://github.com/monarch-initiative/mondo/issues/6008 |   |   | grouping class | MONDO:excludeGroupingClass
MONDO:0016117 | muscular lipidosis' | https://github.com/monarch-initiative/mondo/issues/6008 |   |   | grouping class | MONDO:excludeGroupingClass
MONDO:0006516 | sarcopenia | https://github.com/monarch-initiative/mondo/issues/6008 |   |   | out of scope | MONDO:excludeBiologicalProcess
MONDO:0018344 | periodic paralysis with transient compartment-like syndrome' | https://github.com/monarch-initiative/mondo/issues/6008 |   |   | out of scope | MONDO:excludeGroupingPhenotype
MONDO:0016123 | muscular tumor' | https://github.com/monarch-initiative/mondo/issues/6008 | MONDO:0005864 | muscle cancer' | out of scope | MONDO:excludeGroupingClass
MONDO:0019201 | thyrotoxic periodic paralysis' | https://github.com/monarch-initiative/mondo/issues/6008 |   |   | is a phenotype and not a disease | MONDO:excludePhenotype
MONDO:0005290 | rhabdomyolysis | https://github.com/monarch-initiative/mondo/issues/6008 |   |   | is a phenotype and not a disease | MONDO:excludePhenotype
MONDO:0005307 | contracture | https://github.com/monarch-initiative/mondo/issues/6008 |   |   | is a phenotype and not a disease | MONDO:excludePhenotype

**Comment by sabrinatoro** [comment]
@nicolevasilevsky 
MONDO:0019201 should be obsoleted, but it has a lot of x-ref to omimps, gard,...
Should we still obsolete it? since there are a lot of x-ref, I would like a second brain check. 

Obsoleted this term was discussed on a call with Chris and Peter.

**Comment by cmungall** [comment]
```yaml
id: MONDO:0006516
name: obsolete sarcopenia
def: "OBSOLETE. Progressive decline in muscle mass due to aging which results in decreased functional capacity of muscles." [MESH:D055948]
comment: Reason of obsoletion: out of scope - MONDO:excludeBiologicalProcess. This term represent a natural aging process, and not a disease.
xref: ICD10CM:M62.84 {source="MONDO:obsoleteEquivalent"}
xref: MedDRA:10063024 {source="EFO:1000653"}
xref: MESH:D055948 {source="MONDO:obsoleteEquivalent", source="EFO:1000653"}
property_value: IAO:0000231 OMO:0001000 {source="MONDO:excludeBiologicalProcess"}
property_value: IAO:0000233 "https://github.com/monarch-initiative/mondo/issues/6008" xsd:anyURI
is_obsolete: true
```

FWIW we added sarcopenia to dismech https://github.com/monarch-initiative/dismech/pull/10268
