### ISSUE TITLE
update logical axiom for 'lymphocytic choriomeningitis'

### ISSUE THREAD

**Issue by nicolevasilevsky** [monarch-initiative/mondo#7343]
The current logical axiom is:

'infectious meningitis'
 and ('disease has primary infectious agent' some NCBITaxon_11623)

but NCBITaxon_11623 is obsolete. The NCBITaxon imports need to be refreshed.

The logical def should be updated to:

'viral meningitis'
 and ('disease has primary infectious agent' some NCBITaxon_3052303)

https://www.ncbi.nlm.nih.gov/taxonomy/3052303

**Comment by nicolevasilevsky** [comment]
@twhetzel can you import the new NCBI term that is needed?

**Comment by cmungall** [comment]
```yaml
id: NCBITaxon:3052303
name: Mammarenavirus choriomeningitidis
xref: GC_ID:1
synonym: "LCMV" BROAD []
synonym: "Lymphocytic choriomeningitis mammarenavirus" EXACT []
synonym: "Lymphocytic choriomeningitis virus" EXACT []
synonym: "lymphocytic choriomeningitis virus LCMV" EXACT []
```
