### ISSUE TITLE
Clarify immunodeficiencies involving POLD1 and POLD2

### ISSUE THREAD

**Issue by cmungall** [monarch-initiative/mondo#8082]
We have a term that was added in #5261

```yaml
id: MONDO:0800145
name: non-severe combined immunodeficiency due to polymerase delta deficiency
def: "Any non-severe combined immunodeficiency in which the cause of the disease is variation in the POLD1/POLD2 gene." [PMID:31449058]
subset: clingen {source="MONDO:CLINGEN"}
subset: gard_rare {source="MONDO:GARD"}
subset: rare
is_a: MONDO:0018814 {source="https://orcid.org/0000-0002-7371-8158", source="https://orcid.org/0000-0003-0113-912X"} ! non-SCID combined immunodeficiency
relationship: curated_content_resource https://search.clinicalgenome.org/kb/conditions/MONDO:0800145 {source="MONDO:CLINGEN"}
relationship: RO:0002573 HP:0000007 {source="https://orcid.org/0000-0002-7371-8158", source="https://orcid.org/0000-0003-0113-912X"} ! has modifier Autosomal recessive inheritance
property_value: IAO:0000233 "https://github.com/monarch-initiative/mondo/issues/5261" xsd:anyURI
```

This doesn't conform to a DP. We don't have a DP for disjunctions of genes.

It's important to conform to DPs because otherwise the ontology becomes too hard to manage. For example, we also have:

```yaml
id: MONDO:0970994
name: immunodeficiency 120
xref: OMIM:620836 {source="MONDO:equivalentTo"}
is_a: MONDO:0021094 {source="OMIM:620836", source="https://orcid.org/0000-0002-4142-7153"} ! immunodeficiency disease
```

This is caused by POLD1 (why don't we have the edge linking to gene?)

What is the relationship between these two MONDO IDs? Right now they are unlinked, but they are clearly part of the same spectrum of deficiencies involving one or more parts of the POLD complex.
