### ISSUE TITLE
Check all mappings for dangling pointers

### ISSUE THREAD

**Issue by cmungall** [monarch-initiative/mondo#8727]
Example:

```yaml
id: MONDO:0015547
name: hereditary dementia
def: "An instance of dementia that is caused by an inherited genomic modification in an individual." [MONDO:patterns/hereditary]
subset: disease_grouping
subset: gard_rare {source="GARD:20028", source="MONDO:GARD"}
subset: ordo_group_of_disorders {source="Orphanet:158124"}
subset: otar {source="MONDO:OTAR"}
subset: rare
synonym: "genetic dementia" EXACT [MONDO:patterns/genetic, Orphanet:158124]
xref: GARD:20028 {source="MONDO:GARD"}
xref: MEDGEN:1842422 {source="MONDO:equivalentTo", source="MONDO:MEDGEN"}
xref: Orphanet:158124 {source="MONDO:equivalentTo"}
xref: UMLS:C5680680 {source="MONDO:equivalentTo", source="MONDO:MEDGEN", source="MEDGEN:1842422"}
intersection_of: MONDO:0001627 ! dementia
intersection_of: has_characteristic MONDO:0021152 ! inherited
property_value: IAO:0000233 "https://github.com/monarch-initiative/mondo/issues/5114" xsd:anyURI
property_value: IAO:0000233 "https://github.com/monarch-initiative/mondo/issues/5952" xsd:anyURI
```

(example from #8726)

There is no such GARD disease, 20028 is dangling.

It should be easy to find these via OAK [validate-mappings](https://incatools.github.io/ontology-access-kit/examples/Commands/ValidateMappings.html)

However, when I run this it gives 455 danglers for GARD. These are probably false positives due to the fact the gard ingest has not run since 2024-01.
